language: objective-c
osx_image: xcode7.3

xcode_workspace: Example/Example.xcworkspace
xcode_scheme: Example
podfile: Example/Podfile

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example